### ISSUE TITLE
let dotenv do more work

### ISSUE THREAD

**Issue by maxbeatty** [yTakkar/Handy-Browser-Env#1]
You're currently [duplicating some of what dotenv does under the hood](https://github.com/motdotla/dotenv/blob/v5.0.1/lib/main.js#L61-L75). You could simplify this module to just be:

```js
const
  fs = require('fs'),
  { success, error } = require('handy-log'),
  { config } = require('dotenv'),
  outputFile = './browser-env.js'

const { error:e, parsed } = config()
if (e) {
  return error(e)
}

if (fs.existsSync(outputFile)) {
  fs.unlinkSync(outputFile)
}

fs.appendFileSync(outputFile, `module.exports = ${JSON.stringify(parsed, null, 2)}`)

success(`Successfully created a ${outputFile} file.`)
```

https://runkit.com/maxbeatty/handy-browser-env-1-0-10

**Comment by yTakkar** [comment]
Thnx. Changed it!!
https://github.com/yTakkar/Handy-Client-Env/commit/259cb953d0d208f6fe051e9cf3443cc0fb3b8758
